"""
Tests that areas server fixture cache files match live server responses.

Iterates over fixtures in fixtures/areas_server/*.json, calls the real areas server
for each (lat, lon), and asserts the response equals the cached fixture. Requires
AREAS_SERVER_URL and a running areas server.

Uses urllib so real-server requests are not affected by conftest's requests mocks.
"""
import json
import os
import urllib.error
import urllib.request

import pytest


def _http_get(url: str, timeout: int = 30):
    """GET url; return (status, body, parsed_json_or_none)."""
    req = urllib.request.Request(url, method="GET")
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            status = resp.getcode()
            body = resp.read().decode()
    except urllib.error.HTTPError as e:
        body = e.read().decode() if e.fp else ""
        status = e.code
        try:
            data = json.loads(body) if body.strip().startswith("{") else None
        except json.JSONDecodeError:
            data = None
        return status, body, data
    try:
        data = json.loads(body) if body else None
    except json.JSONDecodeError:
        data = None
    return status, body, data


def _areas_server_base_url():
    from website.settings_utils import get_setting
    url = (get_setting("AREAS_SERVER_URL") or "").strip()
    return url.rstrip("/") if url else ""


def _discover_fixture_files():
    """Yield (filepath, lat, lon) for each fixture in fixtures/areas_server/*.json."""
    tests_dir = os.path.dirname(os.path.abspath(__file__))
    areas_dir = os.path.join(tests_dir, "fixtures", "areas_server")
    if not os.path.isdir(areas_dir):
        return
    for name in sorted(os.listdir(areas_dir)):
        if not name.endswith(".json"):
            continue
        base = name[:-5]
        parts = base.split("_", 1)
        if len(parts) != 2:
            continue
        try:
            lat = float(parts[0])
            lon = float(parts[1])
        except ValueError:
            continue
        yield os.path.join(areas_dir, name), lat, lon


@pytest.fixture(scope="module", autouse=True)
def clear_areas_cache():
    """Clear the areas server response cache at the start of this test module."""
    url = _areas_server_base_url()
    if not url:
        pytest.fail("AREAS_SERVER_URL not set")
    _http_get(url.rstrip("/") + "/cache-clear", timeout=10)


@pytest.fixture
def areas_server_url():
    """Base URL of the areas server from AREAS_SERVER_URL."""
    url = _areas_server_base_url()
    if not url:
        pytest.fail("AREAS_SERVER_URL not set")
    return url


@pytest.fixture
def require_areas_server(areas_server_url):
    """Require the areas server to be up; fail if /health is not ok."""
    try:
        status, _, data = _http_get(areas_server_url + "/health", timeout=5)
    except OSError as e:
        pytest.fail(f"areas server not reachable: {e}")
    if status != 200:
        pytest.fail(f"areas server /health returned {status}")
    if not data or data.get("status") != "ok":
        pytest.fail("areas server unhealthy")
    return areas_server_url


_FIXTURE_PARAMS = list(_discover_fixture_files())
_FIXTURE_IDS = [os.path.basename(p[0]) for p in _FIXTURE_PARAMS]


@pytest.mark.parametrize("fixture_path,lat,lon", _FIXTURE_PARAMS, ids=_FIXTURE_IDS)
def test_fixture_matches_live_response(require_areas_server, fixture_path, lat, lon):
    """
    For each fixture file, call the real areas server with that (lat, lon) and assert
    the response equals the cached fixture. Fixtures are generated by
    fetch_areas_fixtures.py; use the same (lat, lon) and default server params.
    """
    url = require_areas_server
    query_url = f"{url}/query?lat={lat}&lon={lon}"
    status, body, response_data = _http_get(query_url)
    assert status == 200, f"GET {query_url} returned {status}: {body[:500]}"
    assert response_data is not None, "response is not valid JSON"
    assert "admin_hierarchy" in response_data and "protected_areas" in response_data, (
        "response missing admin_hierarchy or protected_areas"
    )

    with open(fixture_path, "r", encoding="utf-8") as f:
        fixture_data = json.load(f)

    assert response_data == fixture_data, (
        f"Live response for ({lat}, {lon}) does not match fixture {os.path.basename(fixture_path)}. "
        "Regenerate with: cd src/tests && python fetch_areas_fixtures.py <AREAS_SERVER_URL>"
    )
