# Generated by Django 6.0.3 on 2026-09-09 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def delete_unowned_example_items(apps, schema_editor):
    ExampleItem = apps.get_model('example_extension', 'ExampleItem')
    ExampleItem.objects.filter(user__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('example_extension', '0002_exampleitem_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(delete_unowned_example_items, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='exampleitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
