name: 'mirror'
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref that triggered this workflow'
        required: false
        default: 'refs/heads/master'

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: Check if master branch
        id: check_branch
        run: |
          if [[ "${{ inputs.ref }}" == "refs/heads/master" ]]; then
            echo "is_master=true" >> $GITHUB_OUTPUT
          else
            echo "is_master=false" >> $GITHUB_OUTPUT
          fi
      
      - name: mirror
        if: steps.check_branch.outputs.is_master == 'true'
        id: mirror
        uses: bridgelightcloud/github-mirror-action@v3
        with:
          origin: 'https://git.evulid.cc/cyberes/geovault.git'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

