plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace = 'com.geovault.tracker.mapcore'
    compileSdk = 36

    defaultConfig {
        minSdk = 34
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation project(':android-common-maps')
    implementation project(':tracker-domain')
    implementation project(':tracker-data')
    implementation project(':tracker-pipeline')
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
}
