"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from website.config_loader import get_config_loader

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load configuration from YAML file
config = get_config_loader()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Can be overridden with SECRET_KEY environment variable
SECRET_KEY = config.get_with_env_override(
    'security.secret_key',
    'SECRET_KEY',
    'django-insecure-f(1zo%f)wm*rl97q0^3!9exd%(s8mz92nagf4q7c2cno&bmyx='
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.get_bool('security.debug', True)

ALLOWED_HOSTS = config.get_list('security.allowed_hosts', ['localhost', '127.0.0.1'])

# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'users',
    'api',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django.contrib.postgres',
    'django.contrib.sites',  # Required by allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'website.middleware.LoggingMiddleware',  # Log BEFORE WhiteNoise to catch static file requests
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'website.middleware.CustomHeaderMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, '../frontend/dist'),
            os.path.join(BASE_DIR, '../allauth templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'website.wsgi.application'
ASGI_APPLICATION = 'website.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config.get_str('database.engine', 'django.contrib.gis.db.backends.postgis'),
        'NAME': config.get_str('database.name', 'geoserver'),
        'USER': config.get_str('database.user', 'geoserver'),
        'PASSWORD': config.get_with_env_override('database.password', 'DB_PASSWORD', ''),
        'HOST': config.get_str('database.host', 'localhost'),
        'PORT': config.get_str('database.port', '5432'),
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# Static files collection directory
# After rebuilding the frontend, run: python manage.py collectstatic --noinput
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise configuration for serving static files in production
# Use StaticFilesStorage (not compressed) since Vite already handles file hashing and compression
# After rebuilding the frontend, run: python manage.py collectstatic --noinput
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Cache configuration
# Using LocMemCache for in-memory caching (works within a single process)
# For production with multiple processes, consider using Redis or Memcached
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',  # Unique identifier for this cache instance
    }
}

# Channel layers configuration for WebSockets
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(
                config.get_str('redis.host', '127.0.0.1'),
                config.get_int('redis.port', 6379)
            )],
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/#/dashboard'
LOGOUT_REDIRECT_URL = '/#/'

# Email Configuration
# Always use SMTP backend
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config.get_str('email.smtp.host', 'smtp.gmail.com')
EMAIL_PORT = config.get_int('email.smtp.port', 587)
EMAIL_USE_TLS = config.get_bool('email.smtp.use_tls', True)
EMAIL_USE_SSL = config.get_bool('email.smtp.use_ssl', False)
EMAIL_HOST_USER = config.get_str('email.smtp.username', '')
EMAIL_HOST_PASSWORD = config.get_with_env_override(
    'email.smtp.password',
    'EMAIL_HOST_PASSWORD',
    ''
)

# Email sender configuration
from_email = config.get_str('email.from_email', 'noreply@example.com')
from_name = config.get_str('email.from_name', '')

# Format "From" email with optional name
if from_name:
    DEFAULT_FROM_EMAIL = f"{from_name} <{from_email}>"
else:
    DEFAULT_FROM_EMAIL = from_email

SERVER_EMAIL = from_email  # Used for error notifications to admins (email only, no name)

# Optional: Subject prefix
EMAIL_SUBJECT_PREFIX = config.get_str('email.subject_prefix', '')

# Django Allauth Configuration
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1  # Required by allauth

# Account settings
ACCOUNT_LOGIN_METHODS = {'email'}  # Use email for authentication
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Require email verification
ACCOUNT_SIGNUP_FIELDS = ['email*', 'email2*', 'password1*', 'password2*']  # Email required, enter twice, no username
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_LOGOUT_ON_GET = False
ACCOUNT_LOGOUT_REDIRECT_URL = LOGOUT_REDIRECT_URL
ACCOUNT_LOGIN_REDIRECT_URL = LOGIN_REDIRECT_URL
ACCOUNT_EMAIL_SUBJECT_PREFIX = EMAIL_SUBJECT_PREFIX
# Use https in production, http in development
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https' if not DEBUG else 'http'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, '../frontend/dist/static'),  # Vue.js static files (JS, CSS with hashes)
    os.path.join(BASE_DIR, '../frontend/dist'),  # Vue.js dist root (for index.html, favicons, etc.)
    os.path.join(BASE_DIR, 'assets'),
]

APPEND_SLASH = True

LOGIN_URL = '/accounts/login/'

CSRF_TRUSTED_ORIGINS = config.get_list('security.csrf_trusted_origins', ['http://localhost:5173'])

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
# HSTS is handled by nginx, not Django
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# File Upload Security Settings
# Note: File type configurations are now centralized in geo_lib.processing.file_types
FILE_UPLOAD_MAX_MEMORY_SIZE = config.get_int('processing.file_upload_max_memory_size', 2 * 1024 * 1024)  # 2MB
DATA_UPLOAD_MAX_MEMORY_SIZE = config.get_int('processing.data_upload_max_memory_size', 2 * 1024 * 1024)  # 2MB

# Security validation settings
SECURE_XML_PARSING = config.get_bool('validation.secure_xml_parsing', True)
ENABLE_FILE_SIGNATURE_VALIDATION = config.get_bool('validation.enable_file_signature_validation', True)
ENABLE_MIME_TYPE_VALIDATION = config.get_bool('validation.enable_mime_type_validation', True)

# GeoJSON API Configuration
# Maximum number of features to return in a single API request
# Set to -1 for no limit (default), or any positive integer to limit features
# 
# Examples:
# MAX_FEATURES_PER_REQUEST = -1    # No limit (return all features)
# MAX_FEATURES_PER_REQUEST = 1000  # Limit to 1000 features per request
# MAX_FEATURES_PER_REQUEST = 500   # Limit to 500 features per request
#
# When a limit is applied, the API will return a warning in the response
# indicating how many features were limited.
MAX_FEATURES_PER_REQUEST = config.get_int('api.max_features_per_request', -1)

# Tile Proxy Cache Configuration
# Directory where proxied tiles will be cached on disk
TILE_CACHE_DIR = config.get_with_env_override('tiles.cache_dir', 'TILE_CACHE_DIR', '/tmp/geoserver-tiles')

# Enable or disable tile caching
TILE_CACHE_ENABLED = config.get_bool_with_env_override('tiles.cache_enabled', 'TILE_CACHE_ENABLED', True)

# Number of days before cached tiles expire
TILE_CACHE_EXPIRY_DAYS = config.get_int('tiles.cache_expiry_days', 30)

# Icon Processing Configuration
# Enable or disable icon processing for KML/KMZ files
_icon_storage_dir = config.get_with_env_override('icons.storage_dir', 'ICON_STORAGE_DIR', None)
if _icon_storage_dir:
    icon_path = Path(_icon_storage_dir)
    # If relative path, make it relative to BASE_DIR
    if not icon_path.is_absolute():
        ICON_STORAGE_DIR = BASE_DIR / icon_path
    else:
        ICON_STORAGE_DIR = icon_path
else:
    ICON_STORAGE_DIR = BASE_DIR / 'data' / 'icons'

ICON_PROCESSING_ENABLED = config.get_bool_with_env_override('icons.processing_enabled', 'ICON_PROCESSING_ENABLED', True)

# Maximum icon file size in bytes (default: 1MB) - for KML/KMZ processing
ICON_MAX_SIZE_BYTES = config.get_int('icons.max_size_bytes', 1048576)

# Maximum icon file size for user uploads (500KB)
ICON_UPLOAD_MAX_SIZE_BYTES = config.get_int('icons.upload_max_size_bytes', 512000)  # 500KB

# Allowed icon extensions for user uploads (restricted subset)
ICON_UPLOAD_ALLOWED_EXTENSIONS = set(config.get_list('icons.upload_allowed_extensions', ['.png', '.jpg', '.jpeg', '.ico']))

# Timeout for fetching remote icons in seconds
ICON_FETCH_TIMEOUT = config.get_float('icons.fetch_timeout', 1.0)

# Allow or disallow hot-linking of hosted icons from external domains
# Default: False (hot-linking disallowed)
ICON_ALLOW_HOTLINKING = config.get_bool('icons.allow_hotlinking', False)

# Reverse Geocoding Configuration
# Overpass API server URL
OVERPASS_API_URL = config.get_with_env_override('geocoding.overpass_api_url', 'OVERPASS_API_URL', 'https://overpass-api.de/api/interpreter')

# Nominatim API server URL
# Nominatim is better at identifying cities/towns from administrative boundaries
NOMINATIM_API_URL = config.get_with_env_override('geocoding.nominatim_api_url', 'NOMINATIM_API_URL', 'https://nominatim.openstreetmap.org')

# Enable or disable reverse geocoding
REVERSE_GEOCODING_ENABLED = config.get_bool_with_env_override('geocoding.enabled', 'REVERSE_GEOCODING_ENABLED', True)

# Distance thresholds for proximity tags (in miles)
CITY_PROXIMITY_MILES = config.get_float('geocoding.city_proximity_miles', 5.0)
LAKE_PROXIMITY_MILES = config.get_float('geocoding.lake_proximity_miles', 1.0)

# Overpass API timeout settings
OVERPASS_TIMEOUT_SECONDS = config.get_int('geocoding.overpass_timeout_seconds', 10)
OVERPASS_REQUEST_TIMEOUT_SECONDS = config.get_int('geocoding.overpass_request_timeout_seconds', 15)

# Import Processing Configuration
# Number of threads to use for parallel feature processing during import
IMPORT_PROCESSING_THREADS = config.get_int('processing.import_threads', 10)

# Processing timeout settings
PROCESSING_TIMEOUT_BASE_SECONDS = config.get_int('processing.timeout_base_seconds', 30)
PROCESSING_TIMEOUT_PER_MB_SECONDS = config.get_int('processing.timeout_per_mb_seconds', 2)

# Duplicate detection settings
DUPLICATE_DETECTION_BATCH_SIZE = config.get_int('processing.duplicate_detection_batch_size', 100)
DUPLICATE_DETECTION_BATCH_THRESHOLD = config.get_int('processing.duplicate_detection_batch_threshold', 1000)

# Bulk database operations
BULK_CREATE_BATCH_SIZE = config.get_int('processing.bulk_create_batch_size', 1000)

# Job cleanup settings
JOB_CLEANUP_INTERVAL_SECONDS = config.get_int('processing.job_cleanup_interval_seconds', 3600)
MAX_JOB_AGE_SECONDS = config.get_int('processing.max_job_age_seconds', 7200)

# API Configuration
TAG_MAX_LENGTH = config.get_int('api.tag_max_length', 255)

# Bounding Box Configuration (hardcoded - not user configurable)
BBOX_WORLD_WIDE_LON_THRESHOLD_1 = 280
BBOX_WORLD_WIDE_LON_THRESHOLD_2 = 270
BBOX_WORLD_WIDE_LAT_THRESHOLD = 170
BBOX_LARGE_EXTENT_LON_THRESHOLD = 200
BBOX_LARGE_EXTENT_LAT_THRESHOLD = 150
BBOX_SUSPICIOUS_RESULT_MIN_COUNT = 10

# Logging configuration with activity tags
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,  # Disable default Django logging
    'formatters': {
        'console': {
            'format': '[{asctime}] {levelname} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',  # Set to DEBUG for troubleshooting
            'class': 'logging.StreamHandler',
            'formatter': 'console',
        },
    },
    'loggers': {
        # Root logger - catches all unhandled loggers
        '': {
            'handlers': ['console'],
            'level': 'WARNING',  # Only show warnings and errors by default
            'propagate': False,
        },
        # Django mail logging
        'django.core.mail': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Users app logging
        'users': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Access logging - HTTP requests, API endpoints, views
        'access': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Import logging - File uploads, processing, import operations
        'import': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # WebSocket logging - Connections, messages, disconnections
        'websocket': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Job logging - Background job processing
        'job': {
            'handlers': ['console'],
            'level': 'DEBUG',  # Set to DEBUG for troubleshooting
            'propagate': False,
        },
        # API app logging - App initialization, background services
        'api.apps': {
            'handlers': ['console'],
            'level': 'DEBUG',  # Set to DEBUG for troubleshooting
            'propagate': False,
        },
        # Database logging - Database operations, queries
        'database': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Security logging - Security events, file validation
        'security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Tile logging - Tile proxy, caching operations
        'tile': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Geocode logging - Geocoding, reverse geocoding
        'geocode': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Startup logging - Server startup checks
        'startup': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Config logging - Configuration loading
        'config': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# MaxMind IP Geolocation Configuration
MAXMIND_DATABASE_PATH = config.get_str('maxmind.database_path', '/var/lib/GeoIP/GeoLite2-Country.mmdb')
