"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import logging
import os
import sys
from pathlib import Path

from website.config_loader import get_config_loader

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load configuration from YAML file
config = get_config_loader()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Can be overridden with SECRET_KEY environment variable
SECRET_KEY = config.get_with_env_override(
    'security.secret_key',
    'SECRET_KEY',
    'django-insecure-f(1zo%f)wm*rl97q0^3!9exd%(s8mz92nagf4q7c2cno&bmyx='
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.get_bool('security.debug', False)

# Site Framework Configuration
# These settings control the Site model used by django.contrib.sites
SITE_DOMAIN = config.get_str('site.domain', 'geovault.example.com')
SITE_NAME = config.get_str('site.name', 'GeoVault')

# Allowed hosts (required when DEBUG is False)
# By default, allow the primary site domain from site.domain
# To add more, set security.additional_allowed_hosts in config.yaml to a list
# of additional domains or proxy IPs
_additional_allowed_hosts = config.get_list('security.additional_allowed_hosts', [])
ALLOWED_HOSTS = [SITE_DOMAIN] + _additional_allowed_hosts

# CORS Configuration
# Additional CORS origins from config (user-specified)
ADDITIONAL_CORS_ORIGINS = config.get_list('security.additional_cors_origins', [])

# Application definition

# Extension Loader
from website.extensions.extension_loader import discover_extensions
# Extensions directory: src/backend/extensions
EXTENSIONS_DIR = BASE_DIR / 'extensions'
# Add to sys.path
if str(EXTENSIONS_DIR) not in sys.path:
    sys.path.insert(0, str(EXTENSIONS_DIR))

# Discover extensions
_extension_apps = discover_extensions(EXTENSIONS_DIR)

INSTALLED_APPS = [
    'daphne',
    'channels',
    'users',
    'api',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django.contrib.postgres',
    'django.contrib.sites',  # Required by allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'oauth2_provider',
] + _extension_apps

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'website.middleware.LoggingMiddleware',  # Log BEFORE WhiteNoise to catch static file requests
    'website.middleware.FixRequestHostMiddleware',  # Fix request host for email URL generation (before allauth)
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'website.middleware.CustomSessionMiddleware',  # Custom SessionMiddleware that prevents cookies for tile requests
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'website.middleware.APIKeyResolutionMiddleware',  # Resolve API key for /api/ so logs show username
    'website.middleware.ActivityTrackingMiddleware',  # Track user activity (after auth)
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'website.middleware.CustomHeaderMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, '../frontend/dist'),
            os.path.join(BASE_DIR, '../allauth templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'website.wsgi.application'
ASGI_APPLICATION = 'website.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Build pool options from config
pool_config = {}
if config.get('database.pool'):
    pool_min = config.get_int('database.pool.min_size', 2)
    pool_max = config.get_int('database.pool.max_size', 8)
    pool_timeout = config.get_int('database.pool.timeout', 10)
    pool_config = {
        'min_size': pool_min,
        'max_size': pool_max,
        'timeout': pool_timeout,
    }

# Build database configuration
db_config = {
    'ENGINE': 'django.contrib.gis.db.backends.postgis',
    'NAME': config.get_str('database.name', 'geovault'),
    'USER': config.get_str('database.user', 'geovault'),
    'PASSWORD': config.get_with_env_override('database.password', 'DB_PASSWORD', ''),
    'HOST': config.get_str('database.host', 'localhost'),
    'PORT': config.get_str('database.port', '5432'),
    # Note: CONN_MAX_AGE may be ignored when using native pooling
    # The pool manages connection lifetime instead
    'CONN_MAX_AGE': config.get_int('database.conn_max_age', 600),
    # Test database configuration - hardcoded for test environment
    # Uses existing database (gv_tests) and drops all tables instead of creating new DB
    # The --reuse-db flag in pytest ensures the database is not created/destroyed
    'TEST': {
        'NAME': 'gv_tests',
        'USER': 'gv_tests',
        'PASSWORD': 'bobjoe99',
        'HOST': '172.0.3.105',
        'PORT': '5432',
    },
}

# Only add OPTIONS if pool is configured
if pool_config:
    db_config['OPTIONS'] = {
        'pool': pool_config,
    }

DATABASES = {
    'default': db_config,
}
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# WhiteNoise configuration for serving static files
# Use StaticFilesStorage (not compressed) since Vite already handles file hashing and compression
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# WhiteNoise settings - serves files directly from source directories
WHITENOISE_USE_FINDERS = True  # Serve directly from STATICFILES_DIRS (no collectstatic needed!)
# Disable auto-refresh in development to improve performance (file watching is handled by runserver)
# Static files are still served, but changes won't trigger automatic reload
WHITENOISE_AUTOREFRESH = False  # Disabled for better dev server performance
WHITENOISE_MANIFEST_STRICT = False  # Don't require manifest file
# WHITENOISE_ROOT serves files at the root URL (e.g., /favicon.ico, /apple-touch-icon.png)
WHITENOISE_ROOT = os.path.join(BASE_DIR, '../frontend/dist')

# Cache control for static files
# Vite adds content hashes to filenames (e.g., index-0MtPbVXm.js), so we can cache aggressively
WHITENOISE_MAX_AGE = 31536000  # 1 year in seconds (60*60*24*365)
# Mark files with content hashes as immutable for optimal caching
WHITENOISE_IMMUTABLE_FILE_TEST = lambda path, url: url.startswith('/static/') and '-' in url.split('/')[-1]

# WhiteNoise CORS header configuration
# By default, WhiteNoise sets Access-Control-Allow-Origin: * for static files.
# We override this to use the site's domain instead.
def whitenoise_add_cors_headers(headers, path, url):
    """Set CORS header for WhiteNoise static files to match site domain."""
    # Use the same logic as CustomHeaderMiddleware to determine the correct origin
    protocol = 'https' if not DEBUG else 'http'
    headers['Access-Control-Allow-Origin'] = f"{protocol}://{SITE_DOMAIN}"

WHITENOISE_ADD_HEADERS_FUNCTION = whitenoise_add_cors_headers

# Cache configuration
# Using LocMemCache for in-memory caching (works within a single process)
# For production with multiple processes, consider using Redis or Memcached
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',  # Unique identifier for this cache instance
    },
    # Separate Redis cache for reverse geocoding results
    # Uses a different Redis DB to persist across restarts (not cleared on startup)
    'reverse_geocoding': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f"redis://{config.get_str('redis.host', '127.0.0.1')}:{config.get_int('redis.port', 6379)}/1",
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'reverse_geocode',
        'TIMEOUT': 30 * 24 * 60 * 60,  # 30 days default timeout
    },
    # Redis cache for rate limiting (works across multiple processes)
    # Uses a different Redis DB for rate limiting counters
    'rate_limiting': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f"redis://{config.get_str('redis.host', '127.0.0.1')}:{config.get_int('redis.port', 6379)}/2",
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 2,  # 2 second timeout for connection
            'SOCKET_TIMEOUT': 2,  # 2 second timeout for operations
        },
        'KEY_PREFIX': 'ratelimit',
        'TIMEOUT': 60,  # Rate limit counters expire after 60 seconds
    }
}

# Channel layers configuration for WebSockets
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(
                config.get_str('redis.host', '127.0.0.1'),
                config.get_int('redis.port', 6379)
            )],
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/#/dashboard'
LOGOUT_REDIRECT_URL = '/#/'

# Email Configuration
# Always use SMTP backend
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config.get_str('email.smtp.host', 'smtp.gmail.com')
EMAIL_PORT = config.get_int('email.smtp.port', 587)
EMAIL_USE_TLS = config.get_bool('email.smtp.use_tls', True)
EMAIL_USE_SSL = config.get_bool('email.smtp.use_ssl', False)
EMAIL_HOST_USER = config.get_str('email.smtp.username', '')
EMAIL_HOST_PASSWORD = config.get_with_env_override(
    'email.smtp.password',
    'EMAIL_HOST_PASSWORD',
    ''
)

# Email sender configuration
from_email = config.get_str('email.from_email', 'noreply@example.com')
from_name = config.get_str('email.from_name', '')

# Format "From" email with optional name
if from_name:
    DEFAULT_FROM_EMAIL = f"{from_name} <{from_email}>"
else:
    DEFAULT_FROM_EMAIL = from_email

SERVER_EMAIL = from_email  # Used for error notifications to admins (email only, no name)

# Optional: Subject prefix
EMAIL_SUBJECT_PREFIX = config.get_str('email.subject_prefix', '')

# Django Allauth Configuration
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'oauth2_provider.backends.OAuth2Backend',
]

SITE_ID = 1  # Required by allauth

# Account settings
ACCOUNT_ADAPTER = 'users.adapters.NoUsernameAccountAdapter'  # Custom adapter to prevent username usage
ACCOUNT_LOGIN_METHODS = {'email'}  # Use email for authentication
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # Require email verification
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']  # Email required, no username
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_LOGOUT_ON_GET = False
ACCOUNT_LOGOUT_REDIRECT_URL = LOGOUT_REDIRECT_URL
ACCOUNT_LOGIN_REDIRECT_URL = LOGIN_REDIRECT_URL
ACCOUNT_EMAIL_SUBJECT_PREFIX = EMAIL_SUBJECT_PREFIX
# Use https in production, http in development
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https' if not DEBUG else 'http'

# OAuth2 Provider (django-oauth-toolkit) for mobile and API clients
# PROTECTED_CLIENT_IDS: applications with these client_ids are shared (e.g. default Android app).
# Only the server can change them; users cannot edit or delete them in the UI.
# ALLOWED_REDIRECT_URI_SCHEMES: permit Android app custom schemes for OAuth callback redirects.
OAUTH2_PROVIDER = {
    'SCOPES': {
        'api': 'Full API access (read and write)',
    },
    'DEFAULT_SCOPES': ['api'],
    'ACCESS_TOKEN_EXPIRE_SECONDS': 3600 * 12,  # 12 hours
    'REFRESH_TOKEN_EXPIRE_SECONDS': 3600 * 24 * 365,  # 1 year
    'PROTECTED_CLIENT_IDS': ['geovault-android'],
    # Redirect URI schemes: only these are accepted when an app registers or uses a redirect_uri.
    # Real security is that the redirect_uri must be in the application's registered list.
    # "custom" (via oauth_custom_scheme monkeypatch) allows any reverse-DNS scheme (e.g. com.*.app).
    'ALLOWED_REDIRECT_URI_SCHEMES': ['http', 'https', 'custom'],
}

STATICFILES_DIRS = [
    # WhiteNoise serves directly from these directories (WHITENOISE_USE_FINDERS = True)
    # Vite's assetsDir: 'static' puts files in dist/static/, which serves at /static/xxx.js
    os.path.join(BASE_DIR, '../frontend/dist/static'),
    os.path.join(BASE_DIR, 'assets'),
]

APPEND_SLASH = True

LOGIN_URL = '/accounts/login/'

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
# HSTS is handled by nginx, not Django
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Reverse Proxy Settings
# When behind a reverse proxy, Django should use the X-Forwarded-Host header
# to determine the correct host for building absolute URLs (e.g., in emails)
USE_X_FORWARDED_HOST = True
# Use X-Forwarded-Proto to determine if the original request was HTTPS
USE_X_FORWARDED_PROTO = True

# CSRF Protection Settings
# CSRF_TRUSTED_ORIGINS is required in Django 4.0+ for HTTPS sites
# Automatically derive from ALLOWED_HOSTS
# Use https:// protocol for production (when not DEBUG), http:// for development
protocol = 'https' if not DEBUG else 'http'
CSRF_TRUSTED_ORIGINS = [f"{protocol}://{host}" for host in ALLOWED_HOSTS if host != '*']
# In DEBUG, also trust Vite dev server origin (host:5173) so accessing via http://HOST:5173 works
if DEBUG:
    CSRF_TRUSTED_ORIGINS += [f"http://{host}:5173" for host in ALLOWED_HOSTS if host != '*']

# Cookie Security Settings (for production with HTTPS)
# In production (when DEBUG=False), cookies should only be sent over HTTPS
CSRF_COOKIE_SECURE = not DEBUG  # True in production, False in development
SESSION_COOKIE_SECURE = not DEBUG  # True in production, False in development
# SameSite prevents CSRF attacks while allowing normal usage
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

# Session Configuration
# Session cookie expires after 60 days of inactivity
SESSION_COOKIE_AGE = 60 * 24 * 60 * 60  # 5,184,000 seconds = 60 days
# Save session on every request to track last activity and extend expiration
SESSION_SAVE_EVERY_REQUEST = True

# File Upload Security Settings
# Note: File type configurations are now centralized in geo_lib.processing.file_types
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB

# GeoJSON API Configuration
# Maximum number of features to return in a single API request
# Set to -1 for no limit (default), or any positive integer to limit features
# 
# Examples:
# MAX_FEATURES_PER_REQUEST = -1    # No limit (return all features)
# MAX_FEATURES_PER_REQUEST = 1000  # Limit to 1000 features per request
# MAX_FEATURES_PER_REQUEST = 500   # Limit to 500 features per request
#
# When a limit is applied, the API will return a warning in the response
# indicating how many features were limited.
MAX_FEATURES_PER_REQUEST = config.get_int('api.max_features_per_request', -1)

# Tile Proxy Cache Configuration
# Directory where proxied tiles will be cached on disk
_tile_cache_dir = config.get_with_env_override('tilesources.cache_dir', 'TILE_CACHE_DIR', None)
if _tile_cache_dir:
    tile_cache_path = Path(_tile_cache_dir)
    # If relative path, make it relative to BASE_DIR
    if not tile_cache_path.is_absolute():
        TILE_CACHE_DIR = BASE_DIR / tile_cache_path
    else:
        TILE_CACHE_DIR = tile_cache_path
else:
    TILE_CACHE_DIR = BASE_DIR / 'data' / 'tile-cache'

# Enable or disable tile caching
TILE_CACHE_ENABLED = config.get_bool_with_env_override('tilesources.cache_enabled', 'TILE_CACHE_ENABLED', True)

# Number of days before cached tiles expire
TILE_CACHE_EXPIRY_DAYS = config.get_int('tilesources.cache_expiry_days', 30)

# Icon Processing Configuration
# Enable or disable icon processing for KML/KMZ files
_icon_storage_dir = config.get_with_env_override('icons.storage_dir', 'ICON_STORAGE_DIR', None)
if _icon_storage_dir:
    icon_path = Path(_icon_storage_dir)
    # If relative path, make it relative to BASE_DIR
    if not icon_path.is_absolute():
        ICON_STORAGE_DIR = BASE_DIR / icon_path
    else:
        ICON_STORAGE_DIR = icon_path
else:
    ICON_STORAGE_DIR = BASE_DIR / 'data' / 'icons'

ICON_PROCESSING_ENABLED = config.get_bool_with_env_override('icons.processing_enabled', 'ICON_PROCESSING_ENABLED', True)

# Maximum icon file size in bytes (default: 1MB) - for KML/KMZ processing
ICON_MAX_SIZE_BYTES = config.get_int('icons.max_size_bytes', 1048576)

# Maximum icon file size for user uploads (500KB)
ICON_UPLOAD_MAX_SIZE_BYTES = config.get_int('icons.upload_max_size_bytes', 512000)  # 500KB

# Allowed icon extensions for user uploads (restricted subset)
ICON_UPLOAD_ALLOWED_EXTENSIONS = set(config.get_list('icons.upload_allowed_extensions', ['.png', '.jpg', '.jpeg', '.ico']))

# Timeout for fetching remote icons in seconds
ICON_FETCH_TIMEOUT = config.get_float('icons.fetch_timeout', 5.0)

# Reverse Geocoding Configuration
# Enable or disable reverse geocoding (enabled by default)
REVERSE_GEOCODING_ENABLED = config.get_bool('reverse_geocoding.enabled', True)

# Distance thresholds for proximity tags (in miles)
CITY_PROXIMITY_MILES = config.get_float('reverse_geocoding.city_proximity_miles', 5.0)
LAKE_PROXIMITY_MILES = config.get_float('reverse_geocoding.lake_proximity_miles', 1.0)

# Overpass API Configuration
# Overpass API server URL
OVERPASS_API_URL = config.get_str('reverse_geocoding.api_url', 'https://overpass.private.coffee/api/interpreter')

# Overpass API timeout settings (in seconds)
OVERPASS_API_TIMEOUT = config.get_int('reverse_geocoding.request_timeout_seconds', 45)

# Overpass API SSL verification setting (enabled by default)
OVERPASS_API_VERIFY_SSL = config.get_bool('reverse_geocoding.verify_ssl', True)

# Elevation API Configuration
# Elevation API server URL (racemap's elevation service)
ELEVATION_API_URL = config.get_str('elevation.api_url', 'https://elevation.racemap.com/api')

# Enable or disable elevation data filling (enabled by default)
ELEVATION_API_ENABLED = config.get_bool('elevation.enabled', True)

# Elevation API timeout settings (in seconds)
ELEVATION_API_TIMEOUT = config.get_int('elevation.timeout_seconds', 30)

# Import Processing Configuration
# Number of threads to use for parallel feature processing during import
IMPORT_PROCESSING_THREADS = config.get_int('processing.import_threads', 10)

# Processing timeout settings
PROCESSING_TIMEOUT_BASE_SECONDS = config.get_int('processing.timeout_base_seconds', 30)
PROCESSING_TIMEOUT_PER_MB_SECONDS = config.get_int('processing.timeout_per_mb_seconds', 2)

# Duplicate detection settings
DUPLICATE_DETECTION_BATCH_SIZE = config.get_int('processing.duplicate_detection_batch_size', 100)
DUPLICATE_DETECTION_BATCH_THRESHOLD = config.get_int('processing.duplicate_detection_batch_threshold', 1000)

# Bulk database operations
BULK_CREATE_BATCH_SIZE = config.get_int('processing.bulk_create_batch_size', 1000)

# Job cleanup settings
JOB_CLEANUP_INTERVAL_SECONDS = config.get_int('processing.job_cleanup_interval_seconds', 3600)
MAX_JOB_AGE_SECONDS = config.get_int('processing.max_job_age_seconds', 7200)

# API Configuration
# Maximum length for tag names.
# This is intentionally configured only in Django settings (not in config.yaml)
# to keep tag validation logic centralized here.
TAG_MAX_LENGTH = 255

# Bounding Box Configuration (hardcoded - not user configurable)
BBOX_WORLD_WIDE_LON_THRESHOLD_1 = 280
BBOX_WORLD_WIDE_LON_THRESHOLD_2 = 270
BBOX_WORLD_WIDE_LAT_THRESHOLD = 170
BBOX_LARGE_EXTENT_LON_THRESHOLD = 200
BBOX_LARGE_EXTENT_LAT_THRESHOLD = 150
BBOX_SUSPICIOUS_RESULT_MIN_COUNT = 10

# Get log level from config (default: info)
_log_level_str = config.get_str('logging.log_level', 'info').lower()
_valid_log_levels = {'critical', 'error', 'warning', 'info', 'debug'}
if _log_level_str not in _valid_log_levels:
    logging.warning(f"Invalid log level '{_log_level_str}', defaulting to 'info'. Valid values: {', '.join(_valid_log_levels)}")
    _log_level_str = 'info'
LOG_LEVEL = _log_level_str.upper()  # Python logging uses uppercase

# Logging configuration with activity tags
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,  # Disable all existing loggers (system loggers)
    'formatters': {
        'console': {
            'format': '[{asctime}] {levelname} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'filters': {
    },
    'handlers': {
        'console': {
            'level': LOG_LEVEL,
            'class': 'logging.StreamHandler',
            'formatter': 'console',
            'stream': 'ext://sys.stdout',
        },
    },
    'loggers': {
        # Root logger - handles all our custom loggers
        '': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        # Explicitly enable our custom tagged loggers (they use lowercase names)
        'processjob': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'replacementcleanupservice': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'startup': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'website.middleware': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        # Enable all loggers under our application namespaces
        'geo_lib': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'api': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'website': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        # Explicitly disable system loggers we don't want
        'daphne': {
            'handlers': [],
            'level': 'WARNING',
            'propagate': False,
        },
        'daphne.server': {
            'handlers': [],
            'level': 'WARNING',
            'propagate': False,
        },
        'daphne.ws_protocol': {
            'handlers': [],
            'level': 'WARNING',
            'propagate': False,
        },
        'daphne.http_protocol': {
            'handlers': [],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.utils.autoreload': {
            'handlers': [],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.server': {
            'handlers': [],
            'level': 'WARNING',
            'propagate': False,
        },
        'channels': {
            'handlers': [],
            'level': 'WARNING',
            'propagate': False,
        },
        'channels.server': {
            'handlers': [],
            'level': 'WARNING',
            'propagate': False,
        },
        'twisted': {
            'handlers': [],
            'level': 'WARNING',
            'propagate': False,
        },
        # Disable caltopo_python library logging
        'caltopo_python': {
            'handlers': [],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# MaxMind IP Geolocation Configuration
# Default to GeoLite2-City database; can be overridden in config.yaml
MAXMIND_DATABASE_PATH = config.get_str('maxmind.database_path', '/var/lib/GeoIP/GeoLite2-City.mmdb')
