pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "android-places"
include ':app'
include ':android-common'
include ':android-common-maps'
project(':android-common').projectDir = file("../android-common")
project(':android-common-maps').projectDir = file("../android-common-maps")
