"""
Geocoding module constants.

Central location for all geocoding-related constants to avoid duplication.
"""

# Cache TTL: 30 days in seconds
REVERSE_GEOCODING_CACHE_TTL = 30 * 24 * 60 * 60

# Coordinate rounding precision for cache keys (~111 meters)
COORDINATE_PRECISION = 3

# Tag prefixes generated by the reverse geocoding system
# This is the SINGLE SOURCE OF TRUTH for all reverse geocoding tag prefixes
# Used by:
# - GeocodingTagGenerator to register system tags
# - regeocode_features management command to filter old tags
REVERSE_GEOCODING_TAG_PREFIXES = [
    # Administrative boundaries
    'city',
    'state',
    'country',
    'county',
    
    # Water bodies
    'lake',
    
    # Recreation
    'ski-resort',
    
    # Protected areas (from classify_protected_area in protected_areas.py)
    'national-park',
    'national-monument',
    'national-forest',
    'national-wildlife-refuge',
    'national-recreation-area',
    'national-historic-site',
    'national-seashore',
    'national-lakeshore',
    'state-park',
    'wilderness',
    'protected-area',  # Default fallback for unclassified protected areas
]
