# Generated by Django 5.2.8 on 2025-11-22 17:19

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(default=list, help_text='Array of tag strings')),
                ('feature_ids', models.JSONField(default=list, help_text='Array of feature IDs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.CharField(db_index=True, help_text='UUID4 share identifier', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_count', models.IntegerField(default=0, help_text='Number of times this share has been accessed')),
                ('include_tags', models.BooleanField(default=False, help_text='Whether to include tags in the shared features')),
                ('collection', models.ForeignKey(help_text='The collection being shared', on_delete=django.db.models.deletion.CASCADE, to='api.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseLogging',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_id', models.UUIDField(blank=True, db_index=True, help_text='UUID to group related log entries', null=True)),
                ('level', models.IntegerField()),
                ('text', models.TextField()),
                ('source', models.CharField(max_length=64)),
                ('attributes', models.JSONField(default=dict, help_text='Key:value pairs for arbitrary attributes')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportQueue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imported', models.BooleanField(default=False)),
                ('unparsable', models.BooleanField(default=False, help_text='True if the file failed to parse and should not be retried')),
                ('geofeatures', models.JSONField(default=list)),
                ('duplicate_features', models.JSONField(default=list, help_text='Features that are duplicates of existing features in the feature store')),
                ('original_filename', models.TextField()),
                ('raw_file', models.TextField(help_text='Raw file content (KML, KMZ, GPX, etc.)')),
                ('geojson_hash', models.CharField(blank=True, help_text='SHA-256 hash of the raw file content for duplicate detection', max_length=64, null=True)),
                ('log_id', models.UUIDField(default=uuid.uuid4, help_text='UUID to group related log entries', null=True, unique=True)),
                ('replacement', models.IntegerField(blank=True, help_text='ID of the existing feature being updated with this replacement upload', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geojson', models.JSONField()),
                ('file_hash', models.CharField(blank=True, help_text="SHA-256 hash of the feature's GeoJSON content", max_length=64, null=True, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, dim=3, null=True, srid=4326)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.importqueue')),
            ],
        ),
        migrations.CreateModel(
            name='TagShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.CharField(db_index=True, help_text='UUID4 or sanitized tag name', max_length=255, unique=True)),
                ('tag', models.CharField(help_text='The tag being shared', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_count', models.IntegerField(default=0, help_text='Number of times this share has been accessed')),
                ('use_tag_as_id', models.BooleanField(default=False, help_text='Whether share_id is the tag name or UUID4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['user', 'created_at'], name='collection_user_created'),
        ),
        migrations.AddIndex(
            model_name='collectionshare',
            index=models.Index(fields=['user', 'created_at'], name='colshare_user_created'),
        ),
        migrations.AddIndex(
            model_name='collectionshare',
            index=models.Index(fields=['share_id'], name='colshare_share_id'),
        ),
        migrations.AddIndex(
            model_name='collectionshare',
            index=models.Index(fields=['collection', 'user'], name='colshare_coll_user'),
        ),
        migrations.AddIndex(
            model_name='databaselogging',
            index=models.Index(fields=['user', 'timestamp'], name='api_databas_user_id_6b56bd_idx'),
        ),
        migrations.AddIndex(
            model_name='databaselogging',
            index=models.Index(fields=['source'], name='api_databas_source_9b476e_idx'),
        ),
        migrations.AddIndex(
            model_name='databaselogging',
            index=models.Index(fields=['level'], name='api_databas_level_af3c18_idx'),
        ),
        migrations.AddIndex(
            model_name='databaselogging',
            index=models.Index(fields=['log_id', 'timestamp'], name='api_databas_log_id_a4bcda_idx'),
        ),
        migrations.AddIndex(
            model_name='databaselogging',
            index=models.Index(fields=['user', 'level', 'timestamp'], name='log_user_level_time'),
        ),
        migrations.AddIndex(
            model_name='databaselogging',
            index=models.Index(fields=['user', 'source', 'timestamp'], name='log_user_source_time'),
        ),
        migrations.AddIndex(
            model_name='databaselogging',
            index=models.Index(fields=['log_id', 'level'], name='log_logid_level'),
        ),
        migrations.AddIndex(
            model_name='databaselogging',
            index=models.Index(fields=['source', 'level', 'timestamp'], name='log_source_level_time'),
        ),
        migrations.AddIndex(
            model_name='importqueue',
            index=models.Index(fields=['user', 'imported', 'timestamp'], name='import_user_imported_time'),
        ),
        migrations.AddIndex(
            model_name='importqueue',
            index=models.Index(fields=['user', 'geojson_hash'], name='import_user_geojson_hash'),
        ),
        migrations.AddIndex(
            model_name='importqueue',
            index=models.Index(fields=['log_id', 'timestamp'], name='import_log_id_time'),
        ),
        migrations.AddIndex(
            model_name='featurestore',
            index=models.Index(fields=['user', 'timestamp'], name='api_feature_user_id_ee48b1_idx'),
        ),
        migrations.AddIndex(
            model_name='featurestore',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geometry'], name='featurestore_geometry_idx'),
        ),
        migrations.AddIndex(
            model_name='featurestore',
            index=models.Index(fields=['file_hash'], name='api_feature_file_ha_c19d31_idx'),
        ),
        migrations.AddIndex(
            model_name='featurestore',
            index=models.Index(fields=['user', 'file_hash'], name='fs_user_hash'),
        ),
        migrations.AddIndex(
            model_name='featurestore',
            index=models.Index(fields=['user', 'timestamp'], name='fs_user_time'),
        ),
        migrations.AddIndex(
            model_name='featurestore',
            index=models.Index(fields=['user', 'source'], name='fs_user_source'),
        ),
        migrations.AddIndex(
            model_name='featurestore',
            index=models.Index(fields=['file_hash', 'timestamp'], name='fs_hash_time'),
        ),
        migrations.AddIndex(
            model_name='tagshare',
            index=models.Index(fields=['user', 'created_at'], name='tagshare_user_created'),
        ),
        migrations.AddIndex(
            model_name='tagshare',
            index=models.Index(fields=['share_id'], name='tagshare_share_id'),
        ),
        migrations.AddIndex(
            model_name='tagshare',
            index=models.Index(fields=['tag', 'user'], name='tagshare_tag_user'),
        ),
    ]
