# Generated by Django 6.0a1 on 2025-11-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importqueue',
            name='replacement',
            field=models.IntegerField(blank=True, help_text='ID of the existing feature being updated with this replacement upload', null=True),
        ),
    ]
