# Generated by Django 6.0a1 on 2025-11-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importqueue',
            name='bulk_operations',
            field=models.JSONField(blank=True, default=dict, help_text='Bulk operations (tags, styling) to apply during import', null=True),
        ),
    ]
