# Generated by Django 6.0a1 on 2025-12-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importqueue',
            name='skipped_feature_ids',
            field=models.JSONField(default=list, help_text='List of feature IDs that are skipped by the user'),
        ),
    ]
