# Generated by Django 6.0a1 on 2026-02-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_featureshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurestore',
            name='scope',
            field=models.CharField(blank=True, db_index=True, default=None, help_text="Scope of the feature (e.g., 'places'). Null means global/standard feature.", max_length=255, null=True),
        ),
    ]
