# Generated by Django 6.0a1 on 2025-11-20 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_importqueue_replacement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.CharField(db_index=True, help_text='UUID4 or sanitized tag name', max_length=255, unique=True)),
                ('tag', models.CharField(help_text='The tag being shared', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_count', models.IntegerField(default=0, help_text='Number of times this share has been accessed')),
                ('use_tag_as_id', models.BooleanField(default=False, help_text='Whether share_id is the tag name or UUID4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='tagshare_user_created'), models.Index(fields=['share_id'], name='tagshare_share_id'), models.Index(fields=['tag', 'user'], name='tagshare_tag_user')],
            },
        ),
    ]
