# Generated by Django 6.0a1 on 2026-01-01 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_featureshare'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalTopoUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='caltopo_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('account_id', models.CharField(help_text='6-character CalTopo account ID', max_length=6)),
                ('credential_id', models.CharField(help_text='12-character CalTopo credential ID', max_length=12)),
                ('credential_key', models.TextField(help_text='CalTopo credential key (should be encrypted at rest - TODO: add encryption when django-cryptography is compatible with Django 6.0)')),
                ('account_id_internet', models.CharField(blank=True, help_text='Optional 6-character internet-specific account ID', max_length=6, null=True)),
                ('imported_features', models.JSONField(default=dict, help_text='Maps CalTopo map_id -> dict of feature_id -> FeatureStore.id. Structure: {map_id: {caltopo_feature_id: geovault_feature_id, ...}, ...}')),
                ('last_synced', models.DateTimeField(blank=True, help_text='Last time CalTopo data was synced', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_caltopouser',
                'indexes': [models.Index(fields=['user'], name='caltopouser_user')],
            },
        ),
    ]
