# Generated by Django 6.0a1 on 2026-01-01 02:28

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_caltopo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caltopouser',
            name='credential_key',
            field=api.fields.EncryptedTextField(help_text='CalTopo credential key (encrypted at rest)'),
        ),
    ]
