# Generated by Django 6.0.3 on 2026-07-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_featurestore_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureshare',
            name='include_tags',
            field=models.BooleanField(default=False, help_text='Whether to include tags in the shared feature'),
        ),
        migrations.AddField(
            model_name='tagshare',
            name='include_tags',
            field=models.BooleanField(default=False, help_text='Whether to include tags in the shared features'),
        ),
    ]
