# Generated by Django 6.0a1 on 2025-11-29 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usersettings_hidden_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='hidden_features',
        ),
    ]
