# Generated by Django 6.0a1 on 2025-11-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tagshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importqueue',
            name='geojson_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the raw file content for duplicate detection', max_length=64, null=True),
        ),
    ]
