# Generated by Django 6.0a1 on 2025-11-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_use_tag_as_id_from_tagshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagshare',
            name='share_id',
            field=models.CharField(db_index=True, help_text='UUID4', max_length=255, unique=True),
        ),
    ]
