# Generated by Django 6.0a1 on 2025-11-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_usersettings_hidden_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='hidden_features',
            field=models.JSONField(default=list, help_text='List of feature IDs hidden on the main map page'),
        ),
    ]
