# Generated by Django 6.0.3 on 2026-09-09 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_include_tags_to_tag_and_feature_share'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='featurestore',
            name='unique_user_geojson_hash',
        ),
        migrations.AddConstraint(
            model_name='featurestore',
            constraint=models.UniqueConstraint(fields=('user', 'scope', 'geojson_hash'), name='unique_user_geojson_hash', nulls_distinct=False, violation_error_message='Feature with this hash already exists for this user'),
        ),
    ]
