# Generated by Django 6.0a1 on 2026-01-01 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_caltopouser_credential_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caltopouser',
            name='account_id_internet',
        ),
    ]
