# Generated by Django 6.0.3 on 2026-09-09 06:00

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_featurestore_unique_user_scope_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionFeatureMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionTagRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_key', models.CharField(max_length=255)),
                ('namespace', models.CharField(max_length=16)),
                ('scope', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportDraftFeature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geojson', models.JSONField()),
                ('geojson_hash', models.CharField(db_index=True, max_length=64)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, dim=3, null=True, srid=4326)),
                ('name', models.TextField(blank=True, default='')),
                ('geometry_type', models.CharField(blank=True, default='', max_length=32)),
                ('sort_lat', models.FloatField(blank=True, null=True)),
                ('sort_lon', models.FloatField(blank=True, null=True)),
                ('spatial_index', models.IntegerField(default=0)),
                ('file_index', models.IntegerField(default=0)),
                ('verdict_kind', models.CharField(choices=[('none', 'None'), ('hash', 'Hash'), ('geometry', 'Geometry')], default='none', max_length=16)),
                ('verdict_scope', models.CharField(choices=[('none', 'None'), ('library', 'Library'), ('draft_queue', 'Draft queue')], default='none', max_length=16)),
                ('match_feature_store_id', models.IntegerField(blank=True, null=True)),
                ('match_queue_id', models.IntegerField(blank=True, null=True)),
                ('match_spatial_index', models.IntegerField(blank=True, null=True)),
                ('match_name', models.TextField(blank=True, default='')),
                ('match_geometry_type', models.CharField(blank=True, default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ShareGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_kind', models.CharField(max_length=32)),
                ('resource_id', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=36, unique=True)),
                ('domain', models.CharField(max_length=32)),
                ('subject_kind', models.CharField(max_length=32)),
                ('subject_ref', models.JSONField()),
                ('audience', models.CharField(max_length=32)),
                ('capabilities', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='importqueue',
            name='duplicate_counts',
            field=models.JSONField(default=dict, help_text='File-wide duplicate counts: {hash, geometry}'),
        ),
        migrations.AddField(
            model_name='importqueue',
            name='queue_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('canceled', 'Canceled'), ('failed', 'Failed'), ('imported', 'Imported')], db_index=True, default='ready', help_text='processing|ready|canceled|failed|imported', max_length=16),
        ),
        migrations.AddField(
            model_name='importqueue',
            name='raw_file_encoding',
            field=models.CharField(choices=[('utf8', 'UTF-8'), ('base64', 'Base64')], default='utf8', help_text='Discriminant for raw_file: utf8 text or base64 bytes', max_length=8),
        ),
        migrations.AddField(
            model_name='importqueue',
            name='skip_intent',
            field=models.JSONField(default=dict, help_text='SkipIntent snapshot: blocked, auto_skipped_geometry, user_skipped, user_restored_geometry'),
        ),
        migrations.AlterField(
            model_name='importqueue',
            name='skipped_feature_ids',
            field=models.JSONField(default=list, help_text='List of feature hashes skipped by the user'),
        ),
        migrations.AddIndex(
            model_name='importqueue',
            index=models.Index(fields=['user', 'queue_status', 'timestamp'], name='import_user_qstatus_time'),
        ),
        migrations.AddField(
            model_name='collectionfeaturemembership',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_pins', to='api.collection'),
        ),
        migrations.AddField(
            model_name='collectionfeaturemembership',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_pins', to='api.featurestore'),
        ),
        migrations.AddField(
            model_name='collectiontagrule',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_rules', to='api.collection'),
        ),
        migrations.AddField(
            model_name='featuretag',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_tags', to='api.featurestore'),
        ),
        migrations.AddField(
            model_name='featuretag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importdraftfeature',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_features', to='api.importqueue'),
        ),
        migrations.AddField(
            model_name='importdraftfeature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharegrant',
            name='grantee_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='collectionfeaturemembership',
            index=models.Index(fields=['feature'], name='col_feat_pin_feat'),
        ),
        migrations.AddConstraint(
            model_name='collectionfeaturemembership',
            constraint=models.UniqueConstraint(fields=('collection', 'feature'), name='uniq_col_feat_pin'),
        ),
        migrations.AddIndex(
            model_name='collectiontagrule',
            index=models.Index(fields=['tag'], name='col_tag_rule_tag'),
        ),
        migrations.AddConstraint(
            model_name='collectiontagrule',
            constraint=models.UniqueConstraint(fields=('collection', 'tag'), name='uniq_col_tag_rule'),
        ),
        migrations.AddIndex(
            model_name='featuretag',
            index=models.Index(fields=['user', 'scope', 'tag_key'], name='ftag_user_scope_key'),
        ),
        migrations.AddIndex(
            model_name='featuretag',
            index=models.Index(fields=['user', 'scope', 'namespace', 'tag_key'], name='ftag_user_scope_ns_key'),
        ),
        migrations.AddIndex(
            model_name='featuretag',
            index=models.Index(fields=['feature'], name='ftag_feature'),
        ),
        migrations.AddIndex(
            model_name='featuretag',
            index=models.Index(fields=['user', 'tag_key'], name='ftag_user_key'),
        ),
        migrations.AddConstraint(
            model_name='featuretag',
            constraint=models.UniqueConstraint(fields=('user', 'feature', 'tag_key', 'namespace', 'scope'), name='uniq_featuretag_user_feat_key_ns_sc', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='importdraftfeature',
            index=models.Index(fields=['queue', 'spatial_index'], name='draft_queue_spatial'),
        ),
        migrations.AddIndex(
            model_name='importdraftfeature',
            index=models.Index(fields=['queue', '-sort_lat', 'sort_lon'], name='draft_queue_sort'),
        ),
        migrations.AddIndex(
            model_name='importdraftfeature',
            index=models.Index(fields=['queue', 'geojson_hash'], name='draft_queue_hash'),
        ),
        migrations.AddIndex(
            model_name='importdraftfeature',
            index=models.Index(fields=['user', 'geojson_hash'], name='draft_user_hash'),
        ),
        migrations.AddIndex(
            model_name='importdraftfeature',
            index=models.Index(fields=['queue', 'verdict_kind'], name='draft_queue_verdict'),
        ),
        migrations.AddIndex(
            model_name='importdraftfeature',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geometry'], name='draft_geometry_idx'),
        ),
        migrations.AddIndex(
            model_name='sharegrant',
            index=models.Index(fields=['resource_kind', 'resource_id'], name='sharegrant_resource'),
        ),
        migrations.AddIndex(
            model_name='sharegrant',
            index=models.Index(fields=['grantee_user'], name='sharegrant_grantee'),
        ),
        migrations.AddConstraint(
            model_name='sharegrant',
            constraint=models.UniqueConstraint(fields=('resource_kind', 'resource_id', 'grantee_user'), name='sharegrant_unique_resource_grantee'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['owner', 'created_at'], name='sharelink_owner_created'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['subject_kind', 'audience'], name='sharelink_kind_audience'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['domain', 'audience'], name='sharelink_domain_audience'),
        ),
        migrations.AddConstraint(
            model_name='sharelink',
            constraint=models.UniqueConstraint(condition=models.Q(('subject_kind', 'feature')), fields=('owner', 'subject_kind', 'subject_ref'), name='sharelink_unique_feature'),
        ),
        migrations.AddConstraint(
            model_name='sharelink',
            constraint=models.UniqueConstraint(condition=models.Q(('subject_kind__in', ['live_track', 'live_track_group'])), fields=('subject_kind', 'subject_ref', 'audience'), name='sharelink_unique_tracker_audience'),
        ),
    ]
