# Generated by Django 6.0a1 on 2026-01-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_account_id_internet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caltopouser',
            name='credential_id',
            field=models.CharField(help_text='12-character CalTopo credential code', max_length=12),
        ),
    ]
