# Generated by Django 6.0.3 on 2026-09-09 06:02

from django.db import migrations


def _tag_list(raw):
    if not isinstance(raw, list):
        return []
    seen = {}
    for tag in raw:
        if isinstance(tag, str) and tag.strip():
            seen.setdefault(tag.strip(), None)
    return list(seen)


def backfill_tags_and_collections(apps, schema_editor):
    FeatureStore = apps.get_model('api', 'FeatureStore')
    FeatureTag = apps.get_model('api', 'FeatureTag')
    Collection = apps.get_model('api', 'Collection')
    CollectionTagRule = apps.get_model('api', 'CollectionTagRule')
    CollectionFeatureMembership = apps.get_model('api', 'CollectionFeatureMembership')

    FeatureTag.objects.all().delete()
    rows = []
    for feature in FeatureStore.objects.iterator(chunk_size=500):
        properties = (feature.geojson or {}).get('properties') if isinstance(feature.geojson, dict) else {}
        if not isinstance(properties, dict):
            properties = {}
        scope = feature.scope if feature.scope else None
        for tag in _tag_list(properties.get('tags')):
            rows.append(FeatureTag(
                user_id=feature.user_id,
                feature_id=feature.id,
                tag_key=tag,
                namespace='user',
                scope=scope,
            ))
        for tag in _tag_list(properties.get('system_tags')):
            rows.append(FeatureTag(
                user_id=feature.user_id,
                feature_id=feature.id,
                tag_key=tag,
                namespace='system',
                scope=scope,
            ))
        if len(rows) >= 1000:
            FeatureTag.objects.bulk_create(rows, ignore_conflicts=True)
            rows = []
    if rows:
        FeatureTag.objects.bulk_create(rows, ignore_conflicts=True)

    main_map_tags = set(
        FeatureTag.objects.filter(scope__isnull=True).values_list('user_id', 'tag_key')
    )
    owned_main_map = {
        (row['user_id'], row['id'])
        for row in FeatureStore.objects.filter(scope__isnull=True).exclude(geometry__isnull=True).values('user_id', 'id')
    }

    CollectionTagRule.objects.all().delete()
    CollectionFeatureMembership.objects.all().delete()
    rule_rows = []
    pin_rows = []
    for collection in Collection.objects.iterator(chunk_size=200):
        for tag in _tag_list(collection.tags):
            if (collection.user_id, tag) in main_map_tags:
                rule_rows.append(CollectionTagRule(collection=collection, tag=tag))
        feature_ids = collection.feature_ids if isinstance(collection.feature_ids, list) else []
        seen = set()
        for feature_id in feature_ids:
            if not isinstance(feature_id, int) or feature_id in seen:
                continue
            seen.add(feature_id)
            if (collection.user_id, feature_id) in owned_main_map:
                pin_rows.append(CollectionFeatureMembership(collection=collection, feature_id=feature_id))
    if rule_rows:
        CollectionTagRule.objects.bulk_create(rule_rows, ignore_conflicts=True)
    if pin_rows:
        CollectionFeatureMembership.objects.bulk_create(pin_rows, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_collectionfeaturemembership_collectiontagrule_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_tags_and_collections, noop_reverse),
    ]
