# Generated by Django 6.0.3 on 2026-09-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_backfill_featuretag_and_collection_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='feature_ids',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='tags',
        ),
    ]
