# Generated by Django 6.0a1 on 2025-11-21 01:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_collection'),
    ]

    operations = [
        # Since the table is empty, we can safely drop and recreate the id column
        # Step 1: Drop the primary key constraint and the old integer id column, then add UUID column
        migrations.RunSQL(
            sql="""
                ALTER TABLE api_collection DROP CONSTRAINT api_collection_pkey;
                ALTER TABLE api_collection DROP COLUMN id;
                ALTER TABLE api_collection ADD COLUMN id UUID PRIMARY KEY DEFAULT gen_random_uuid();
            """,
            reverse_sql="""
                ALTER TABLE api_collection DROP COLUMN id;
                ALTER TABLE api_collection ADD COLUMN id SERIAL PRIMARY KEY;
            """
        ),
        # Step 2: Update Django's model state to reflect the change
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
