# Generated by Django 6.0.3 on 2026-09-09 06:07

from django.db import migrations


DOMAIN_MAP = "map"
DOMAIN_LIVE_TRACK = "live_track"
KIND_TAG = "tag"
KIND_COLLECTION = "collection"
KIND_FEATURE = "feature"
KIND_LIVE_TRACK = "live_track"
KIND_LIVE_TRACK_GROUP = "live_track_group"
AUDIENCE_WORLD = "world"
AUDIENCE_AUTHENTICATED = "authenticated"


def _capabilities(include_tags=False, allow_downloads=False):
    return {
        "allow_downloads": bool(allow_downloads),
        "include_tags": bool(include_tags),
    }


def _copy_link(ShareLink, *, token, owner_id, domain, subject_kind, subject_ref, audience, created_at, access_count, capabilities):
    if owner_id is None or not token:
        return
    normalized = str(token).strip().lower()
    if ShareLink.objects.filter(token=normalized).exists():
        return
    link = ShareLink.objects.create(
        token=normalized,
        owner_id=owner_id,
        domain=domain,
        subject_kind=subject_kind,
        subject_ref=subject_ref,
        audience=audience,
        capabilities=capabilities,
        access_count=access_count or 0,
    )
    if created_at is not None:
        ShareLink.objects.filter(pk=link.pk).update(created_at=created_at)


def copy_legacy_shares(apps, schema_editor):
    ShareLink = apps.get_model("api", "ShareLink")
    ShareGrant = apps.get_model("api", "ShareGrant")
    TagShare = apps.get_model("api", "TagShare")
    CollectionShare = apps.get_model("api", "CollectionShare")
    FeatureShare = apps.get_model("api", "FeatureShare")

    for row in TagShare.objects.all().iterator():
        _copy_link(
            ShareLink,
            token=row.share_id,
            owner_id=row.user_id,
            domain=DOMAIN_MAP,
            subject_kind=KIND_TAG,
            subject_ref=row.tag,
            audience=AUDIENCE_WORLD,
            created_at=row.created_at,
            access_count=row.access_count,
            capabilities=_capabilities(row.include_tags, row.allow_downloads),
        )

    for row in CollectionShare.objects.all().iterator():
        _copy_link(
            ShareLink,
            token=row.share_id,
            owner_id=row.user_id,
            domain=DOMAIN_MAP,
            subject_kind=KIND_COLLECTION,
            subject_ref=str(row.collection_id),
            audience=AUDIENCE_WORLD,
            created_at=row.created_at,
            access_count=row.access_count,
            capabilities=_capabilities(row.include_tags, row.allow_downloads),
        )

    for row in FeatureShare.objects.all().iterator():
        _copy_link(
            ShareLink,
            token=row.share_id,
            owner_id=row.user_id,
            domain=DOMAIN_MAP,
            subject_kind=KIND_FEATURE,
            subject_ref=row.feature_id,
            audience=AUDIENCE_WORLD,
            created_at=row.created_at,
            access_count=row.access_count,
            capabilities=_capabilities(row.include_tags, row.allow_downloads),
        )

    LiveTrack = apps.get_model("live_track", "LiveTrack")
    LiveTrackGroup = apps.get_model("live_track", "LiveTrackGroup")
    track_owners = dict(LiveTrack.objects.values_list("id", "user_id"))
    group_owners = dict(LiveTrackGroup.objects.values_list("id", "user_id"))

    LiveTrackWorldShare = apps.get_model("live_track", "LiveTrackWorldShare")
    for row in LiveTrackWorldShare.objects.all().iterator():
        _copy_link(
            ShareLink,
            token=row.share_id,
            owner_id=track_owners.get(row.track_id),
            domain=DOMAIN_LIVE_TRACK,
            subject_kind=KIND_LIVE_TRACK,
            subject_ref=str(row.track_id),
            audience=AUDIENCE_WORLD,
            created_at=row.created_at,
            access_count=0,
            capabilities=_capabilities(),
        )

    LiveTrackInternalShare = apps.get_model("live_track", "LiveTrackInternalShare")
    for row in LiveTrackInternalShare.objects.all().iterator():
        _copy_link(
            ShareLink,
            token=row.share_id,
            owner_id=row.user_id or track_owners.get(row.track_id),
            domain=DOMAIN_LIVE_TRACK,
            subject_kind=KIND_LIVE_TRACK,
            subject_ref=str(row.track_id),
            audience=AUDIENCE_AUTHENTICATED,
            created_at=row.created_at,
            access_count=0,
            capabilities=_capabilities(),
        )

    LiveTrackGroupWorldShare = apps.get_model("live_track", "LiveTrackGroupWorldShare")
    for row in LiveTrackGroupWorldShare.objects.all().iterator():
        _copy_link(
            ShareLink,
            token=row.share_id,
            owner_id=group_owners.get(row.group_id),
            domain=DOMAIN_LIVE_TRACK,
            subject_kind=KIND_LIVE_TRACK_GROUP,
            subject_ref=str(row.group_id),
            audience=AUDIENCE_WORLD,
            created_at=row.created_at,
            access_count=0,
            capabilities=_capabilities(),
        )

    LiveTrackGroupInternalShare = apps.get_model("live_track", "LiveTrackGroupInternalShare")
    for row in LiveTrackGroupInternalShare.objects.all().iterator():
        _copy_link(
            ShareLink,
            token=row.share_id,
            owner_id=row.user_id or group_owners.get(row.group_id),
            domain=DOMAIN_LIVE_TRACK,
            subject_kind=KIND_LIVE_TRACK_GROUP,
            subject_ref=str(row.group_id),
            audience=AUDIENCE_AUTHENTICATED,
            created_at=row.created_at,
            access_count=0,
            capabilities=_capabilities(),
        )

    LiveTrackShare = apps.get_model("live_track", "LiveTrackShare")
    for row in LiveTrackShare.objects.all().iterator():
        ShareGrant.objects.get_or_create(
            resource_kind=KIND_LIVE_TRACK,
            resource_id=str(row.track_id),
            grantee_user_id=row.shared_with_id,
        )

    LiveTrackGroupShare = apps.get_model("live_track", "LiveTrackGroupShare")
    for row in LiveTrackGroupShare.objects.all().iterator():
        ShareGrant.objects.get_or_create(
            resource_kind=KIND_LIVE_TRACK_GROUP,
            resource_id=str(row.group_id),
            grantee_user_id=row.shared_with_id,
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_drop_collection_json_membership"),
        ("live_track", "0004_livetrackgroupinternalshare_livetrackinternalshare"),
    ]

    operations = [
        migrations.RunPython(copy_legacy_shares, noop_reverse),
    ]
