# Generated by Django 6.0a1 on 2025-11-21 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_collection_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.CharField(db_index=True, help_text='UUID4 share identifier', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_count', models.IntegerField(default=0, help_text='Number of times this share has been accessed')),
                ('collection', models.ForeignKey(help_text='The collection being shared', on_delete=django.db.models.deletion.CASCADE, to='api.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='collectionshare_user_created'), models.Index(fields=['share_id'], name='collectionshare_share_id'), models.Index(fields=['collection', 'user'], name='collectionshare_collection_user')],
            },
        ),
    ]
