# Generated by Django 6.0.3 on 2026-09-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_copy_legacy_shares_to_sharelink'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='collectionshare',
            name='colshare_user_created',
        ),
        migrations.RemoveIndex(
            model_name='collectionshare',
            name='colshare_share_id',
        ),
        migrations.RemoveIndex(
            model_name='collectionshare',
            name='colshare_coll_user',
        ),
        migrations.RemoveIndex(
            model_name='featureshare',
            name='featshare_user_created',
        ),
        migrations.RemoveIndex(
            model_name='featureshare',
            name='featshare_share_id',
        ),
        migrations.RemoveIndex(
            model_name='featureshare',
            name='featshare_feat_user',
        ),
        migrations.RemoveIndex(
            model_name='tagshare',
            name='tagshare_user_created',
        ),
        migrations.RemoveIndex(
            model_name='tagshare',
            name='tagshare_share_id',
        ),
        migrations.RemoveIndex(
            model_name='tagshare',
            name='tagshare_tag_user',
        ),
        migrations.RemoveField(
            model_name='featureshare',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='featureshare',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tagshare',
            name='user',
        ),
        migrations.DeleteModel(
            name='CollectionShare',
        ),
        migrations.DeleteModel(
            name='FeatureShare',
        ),
        migrations.DeleteModel(
            name='TagShare',
        ),
    ]
