# Generated by Django 6.0a1 on 2025-11-21 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_collection_share'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='collectionshare',
            new_name='colshare_user_created',
            old_name='collectionshare_user_created',
        ),
        migrations.RenameIndex(
            model_name='collectionshare',
            new_name='colshare_share_id',
            old_name='collectionshare_share_id',
        ),
        migrations.RenameIndex(
            model_name='collectionshare',
            new_name='colshare_coll_user',
            old_name='collectionshare_collection_user',
        ),
    ]
