# Generated by Django 6.0.3 on 2026-09-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_legacy_map_share_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importqueue',
            name='duplicate_features',
        ),
        migrations.RemoveField(
            model_name='importqueue',
            name='geofeatures',
        ),
        migrations.RemoveField(
            model_name='importqueue',
            name='skipped_feature_ids',
        ),
    ]
