# Generated by Django 6.0a1 on 2026-02-13 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_featurestore_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceMetadata',
            fields=[
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='place_metadata', serialize=False, to='api.featurestore')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_navigated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
