# Generated by Django 6.0a1 on 2025-11-16 01:40

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportQueue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imported', models.BooleanField(default=False)),
                ('unparsable', models.BooleanField(default=False, help_text='True if the file failed to parse and should not be retried')),
                ('geofeatures', models.JSONField(default=list)),
                ('duplicate_features', models.JSONField(default=list, help_text='Features that are duplicates of existing features in the feature store')),
                ('original_filename', models.TextField()),
                ('raw_kml', models.TextField()),
                ('geojson_hash', models.CharField(blank=True, help_text='SHA-256 hash of the normalized GeoJSON FeatureCollection content', max_length=64, null=True)),
                ('log_id', models.UUIDField(default=uuid.uuid4, help_text='UUID to group related log entries', null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geojson', models.JSONField()),
                ('geojson_hash', models.CharField(blank=True, help_text="SHA-256 hash of the feature's GeoJSON content", max_length=64, null=True, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, dim=3, null=True, srid=4326)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.importqueue')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseLogging',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_id', models.UUIDField(blank=True, db_index=True, help_text='UUID to group related log entries', null=True)),
                ('level', models.IntegerField()),
                ('text', models.TextField()),
                ('source', models.CharField(max_length=64)),
                ('attributes', models.JSONField(default=dict, help_text='Key:value pairs for arbitrary attributes')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'timestamp'], name='api_databas_user_id_6b56bd_idx'), models.Index(fields=['source'], name='api_databas_source_9b476e_idx'), models.Index(fields=['level'], name='api_databas_level_af3c18_idx'), models.Index(fields=['log_id', 'timestamp'], name='api_databas_log_id_a4bcda_idx'), models.Index(fields=['user', 'level', 'timestamp'], name='log_user_level_time'), models.Index(fields=['user', 'source', 'timestamp'], name='log_user_source_time'), models.Index(fields=['log_id', 'level'], name='log_logid_level'), models.Index(fields=['source', 'level', 'timestamp'], name='log_source_level_time')],
            },
        ),
        migrations.AddIndex(
            model_name='importqueue',
            index=models.Index(fields=['user', 'imported', 'timestamp'], name='import_user_imported_time'),
        ),
        migrations.AddIndex(
            model_name='importqueue',
            index=models.Index(fields=['user', 'geojson_hash'], name='import_user_geojson_hash'),
        ),
        migrations.AddIndex(
            model_name='importqueue',
            index=models.Index(fields=['log_id', 'timestamp'], name='import_log_id_time'),
        ),
        migrations.AddIndex(
            model_name='featurestore',
            index=models.Index(fields=['user', 'timestamp'], name='api_feature_user_id_ee48b1_idx'),
        ),
        migrations.AddIndex(
            model_name='featurestore',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geometry'], name='featurestore_geometry_idx'),
        ),
        migrations.AddIndex(
            model_name='featurestore',
            index=models.Index(fields=['geojson_hash'], name='api_feature_geojson_d8bfa0_idx'),
        ),
        migrations.AddIndex(
            model_name='featurestore',
            index=models.Index(fields=['user', 'geojson_hash'], name='fs_user_hash'),
        ),
        migrations.AddIndex(
            model_name='featurestore',
            index=models.Index(fields=['user', 'timestamp'], name='fs_user_time'),
        ),
        migrations.AddIndex(
            model_name='featurestore',
            index=models.Index(fields=['user', 'source'], name='fs_user_source'),
        ),
        migrations.AddIndex(
            model_name='featurestore',
            index=models.Index(fields=['geojson_hash', 'timestamp'], name='fs_hash_time'),
        ),
    ]
