# Generated by Django 6.0a1 on 2025-11-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_raw_kml_to_raw_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importqueue',
            name='raw_file',
            field=models.TextField(help_text='Raw file content (KML, KMZ, GPX, etc.)'),
        ),
    ]
