# Generated by Django 6.0a1 on 2025-11-20 04:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_importqueue_raw_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='featurestore',
            name='api_feature_geojson_d8bfa0_idx',
        ),
        migrations.RemoveIndex(
            model_name='featurestore',
            name='fs_user_hash',
        ),
        migrations.RemoveIndex(
            model_name='featurestore',
            name='fs_hash_time',
        ),
        migrations.AddField(
            model_name='featurestore',
            name='file_hash',
            field=models.CharField(blank=True, help_text="SHA-256 hash of the feature's GeoJSON content", max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='featurestore',
            index=models.Index(fields=['file_hash'], name='api_feature_file_ha_c19d31_idx'),
        ),
        migrations.AddIndex(
            model_name='featurestore',
            index=models.Index(fields=['user', 'file_hash'], name='fs_user_hash'),
        ),
        migrations.AddIndex(
            model_name='featurestore',
            index=models.Index(fields=['file_hash', 'timestamp'], name='fs_hash_time'),
        ),
        migrations.RemoveField(
            model_name='featurestore',
            name='geojson_hash',
        ),
    ]
