# Generated by Django 6.0a1 on 2025-11-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_collection_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionshare',
            name='include_tags',
            field=models.BooleanField(default=False, help_text='Whether to include tags in the shared features'),
        ),
    ]
