"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# TODO: user config
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f(1zo%f)wm*rl97q0^3!9exd%(s8mz92nagf4q7c2cno&bmyx='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']  # Configure for production

# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'users',
    'api',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django.contrib.postgres',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'website.middleware.CustomHeaderMiddleware',
]

ROOT_URLCONF = 'website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, '../geo-frontend/dist')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'website.wsgi.application'
ASGI_APPLICATION = 'website.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


# TODO: user config
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'geoserver',
        'USER': 'geoserver',
        'PASSWORD': 'juu1waigu1pookee1ohcierahMoofie3',
        'HOST': '172.0.2.105',
        'PORT': '',
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Cache configuration (using dummy cache since we removed caching)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}

# Channel layers configuration for WebSockets
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/#/dashboard'
LOGOUT_REDIRECT_URL = '/#/'

# TODO: https://realpython.com/django-user-management/#send-password-reset-links

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, '../geo-frontend/dist/static'),
]

APPEND_SLASH = True

LOGIN_URL = '/account/login'

CSRF_TRUSTED_ORIGINS = ['http://localhost:5173']

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# File Upload Security Settings
# Note: File type configurations are now centralized in geo_lib.processing.file_types
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024  # 2MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024  # 2MB

# Security validation settings
SECURE_XML_PARSING = True
ENABLE_FILE_SIGNATURE_VALIDATION = True
ENABLE_MIME_TYPE_VALIDATION = True

# GeoJSON API Configuration
# Maximum number of features to return in a single API request
# Set to -1 for no limit (default), or any positive integer to limit features
# 
# Examples:
# MAX_FEATURES_PER_REQUEST = -1    # No limit (return all features)
# MAX_FEATURES_PER_REQUEST = 1000  # Limit to 1000 features per request
# MAX_FEATURES_PER_REQUEST = 500   # Limit to 500 features per request
#
# When a limit is applied, the API will return a warning in the response
# indicating how many features were limited.
MAX_FEATURES_PER_REQUEST = -1

# Tile Proxy Cache Configuration
# Directory where proxied tiles will be cached on disk
# Default: /tmp/geoserver-tiles (can be overridden via environment variable)
TILE_CACHE_DIR = os.environ.get('TILE_CACHE_DIR', '/tmp/geoserver-tiles')

# Enable or disable tile caching (default: True)
TILE_CACHE_ENABLED = os.environ.get('TILE_CACHE_ENABLED', 'True').lower() == 'true'

# Number of days before cached tiles expire (default: 30 days)
TILE_CACHE_EXPIRY_DAYS = int(os.environ.get('TILE_CACHE_EXPIRY_DAYS', '30'))

# Icon Processing Configuration
# Enable or disable icon processing for KML/KMZ files (default: False)
ICON_PROCESSING_ENABLED = os.environ.get('ICON_PROCESSING_ENABLED', 'True').lower() == 'true'

# Directory where processed icons will be stored
# Default: BASE_DIR / 'data' / 'icons' (can be overridden via environment variable)
ICON_STORAGE_DIR = Path(os.environ.get('ICON_STORAGE_DIR', BASE_DIR / 'data' / 'icons'))

# Maximum icon file size in bytes (default: 1MB)
ICON_MAX_SIZE_BYTES = int(os.environ.get('ICON_MAX_SIZE_BYTES', '1048576'))

# Timeout for fetching remote icons in seconds (default: 1 second)
ICON_FETCH_TIMEOUT = float(os.environ.get('ICON_FETCH_TIMEOUT', '1.0'))

# Reverse Geocoding Configuration
# Overpass API server URL (default: public OSM Overpass)
OVERPASS_API_URL = os.environ.get('OVERPASS_API_URL', 'https://overpass-api.de/api/interpreter')

# Nominatim API server URL (default: public Nominatim)
# Nominatim is better at identifying cities/towns from administrative boundaries
NOMINATIM_API_URL = os.environ.get('NOMINATIM_API_URL', 'https://nominatim.openstreetmap.org')

# Enable or disable reverse geocoding (default: True)
REVERSE_GEOCODING_ENABLED = os.environ.get('REVERSE_GEOCODING_ENABLED', 'True').lower() == 'true'

# Distance thresholds for proximity tags (in miles)
CITY_PROXIMITY_MILES = float(os.environ.get('CITY_PROXIMITY_MILES', '5.0'))
LAKE_PROXIMITY_MILES = float(os.environ.get('LAKE_PROXIMITY_MILES', '1.0'))

# Import Processing Configuration
# Number of threads to use for parallel feature processing during import
# Default: 4 threads (can be overridden via environment variable)
IMPORT_PROCESSING_THREADS = int(os.environ.get('IMPORT_PROCESSING_THREADS', '10'))

# Logging configuration for security events
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'geo_lib.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}
