"""
Golden-master corpus tests for geo_lib.togeojson.

For every KML/KMZ/GPX file in the (externally-hosted, symlinked)
geovault-tests corpus, this asserts that running the file through GeoVault's
*real* production preprocessing (KMLProcessor/GPXProcessor/secure_kmz_to_kml
-- imported directly, not reimplemented) and then through this Python port
produces exactly the same GeoJSON as the cached expected-geojson/ output,
which was generated by running the real Node.js @tmcw/togeojson v7.1.2
against the same production-preprocessed content (see
geovault-tests/Scripts/generate-golden-master.js).

Excluded from the corpus walk: `unsafe/` (security-rejection fixtures that
never reach the converter in production) and `Scripts/`/`expected-geojson/`
(the golden-master tooling itself, not test input).

Any corpus file without a cached expected-geojson/ entry (currently just
Grey Harbor County/NWI_Wetlands.kmz, whose decompressed KML exceeds
production's 200MB KMZ bound and so is never converted in production
either) is skipped rather than failed.
"""

import json
from pathlib import Path

import defusedxml.minidom as minidom
import pytest

from geo_lib.processing.processors.gpx_processor import GPXProcessor
from geo_lib.processing.processors.kml_processor import KMLProcessor
from geo_lib.security.secure_file_validator import secure_kmz_to_kml
from geo_lib.togeojson import gpx, kml
from tests.conftest import get_geovault_tests_dir

_EXCLUDED_DIR_NAMES = {"unsafe", "Scripts", "expected-geojson", ".git"}
_CORPUS_EXTENSIONS = {".kml", ".kmz", ".gpx"}


def _discover_corpus_files(corpus_dir: Path) -> list[Path]:
    files = []
    for path in corpus_dir.rglob("*"):
        if not path.is_file():
            continue
        if path.suffix.lower() not in _CORPUS_EXTENSIONS:
            continue
        if _EXCLUDED_DIR_NAMES & set(path.relative_to(corpus_dir).parts[:-1]):
            continue
        files.append(path)
    return sorted(files)


def pytest_generate_tests(metafunc):
    if "corpus_file_rel_path" not in metafunc.fixturenames:
        return

    corpus_dir = get_geovault_tests_dir()
    if corpus_dir is None:
        metafunc.parametrize(
            "corpus_file_rel_path",
            [pytest.param(None, id="geovault-tests-not-configured")],
        )
        return

    files = _discover_corpus_files(corpus_dir)
    rel_paths = [str(f.relative_to(corpus_dir)) for f in files]
    metafunc.parametrize("corpus_file_rel_path", rel_paths, ids=rel_paths)


def _assert_geojson_matches(actual: dict, expected: dict, rel_path: str) -> None:
    """
    Compare two FeatureCollections without handing a full mismatch to
    pytest's assertion-rewriting diff machinery.

    Some corpus files (e.g. Roads.kml) convert to thousands of features and
    several megabytes of JSON. A plain `assert actual == expected` is fine
    when it passes (dict equality short-circuits on the first difference
    internally), but on any real *mismatch* pytest recursively walks and
    pretty-prints both structures to build a diff -- which is combinatorially
    expensive on collections this large and can hang for minutes on a single
    failing case. Raising a plain `AssertionError` ourselves (rather than
    going through a bytecode-rewritten `assert` statement) skips that diff
    renderer entirely and instead points straight at the first differing
    feature.
    """
    if actual.get("type") != expected.get("type"):
        raise AssertionError(f"{rel_path}: type {actual.get('type')!r} != {expected.get('type')!r}")

    actual_features = actual.get("features", [])
    expected_features = expected.get("features", [])
    if len(actual_features) != len(expected_features):
        raise AssertionError(f"{rel_path}: {len(actual_features)} features != {len(expected_features)} expected")

    for index, (actual_feature, expected_feature) in enumerate(zip(actual_features, expected_features)):
        if actual_feature != expected_feature:
            raise AssertionError(
                f"{rel_path}: features[{index}] mismatch\n"
                f"  actual:   {actual_feature!r}\n"
                f"  expected: {expected_feature!r}"
            )

    actual_extra = {k: v for k, v in actual.items() if k != "features"}
    expected_extra = {k: v for k, v in expected.items() if k != "features"}
    if actual_extra != expected_extra:
        raise AssertionError(
            f"{rel_path}: top-level keys (excluding features) mismatch\n"
            f"  actual:   {actual_extra!r}\n"
            f"  expected: {expected_extra!r}"
        )


def _convert(corpus_dir: Path, rel_path: str) -> dict:
    file_path = corpus_dir / rel_path
    ext = file_path.suffix.lower()
    raw_bytes = file_path.read_bytes()

    if ext == ".gpx":
        content = GPXProcessor(file_data=raw_bytes, filename=file_path.name)._decode_content()
        return gpx(minidom.parseString(content))

    if ext == ".kml":
        content = KMLProcessor(file_data=raw_bytes, filename=file_path.name)._prepare_kml_content()
        return kml(minidom.parseString(content))

    if ext == ".kmz":
        # KMZProcessor bypasses KMLProcessor's namespace-prefix stripping
        # entirely -- it calls secure_kmz_to_kml() directly.
        content = secure_kmz_to_kml(raw_bytes)
        return kml(minidom.parseString(content))

    raise AssertionError(f"unexpected corpus extension: {ext}")


class TestGoldenMasterCorpus:
    def test_matches_real_togeojson_output(self, corpus_file_rel_path):
        if corpus_file_rel_path is None:
            pytest.skip(
                "geovault-tests corpus not found -- set GEOVAULT_TESTS_DIR or "
                "symlink it at src/tests/files/geovault-tests"
            )

        corpus_dir = get_geovault_tests_dir()
        expected_path = corpus_dir / "expected-geojson" / f"{corpus_file_rel_path}.json"

        if not expected_path.exists():
            pytest.skip(
                f"No cached golden master for '{corpus_file_rel_path}' "
                "(likely excluded at generation time, e.g. exceeds the "
                "production KMZ decompressed-size bound)"
            )

        expected = json.loads(expected_path.read_text(encoding="utf-8"))
        actual = _convert(corpus_dir, corpus_file_rel_path)

        _assert_geojson_matches(actual, expected, corpus_file_rel_path)
