"""
Geocoding module constants.

Central location for all reverse_geocoding-related constants to avoid duplication.
"""

# Cache TTL: 30 days in seconds
REVERSE_GEOCODING_CACHE_TTL = 30 * 24 * 60 * 60

# Coordinate rounding precision for cache keys (~111 meters)
COORDINATE_PRECISION = 3

# Max distance (meters) from a waterway centerline to add a waterway tag (rivers are linestrings, not polygons).
# Use within 300 ft to match areas server default; no separate "on water" check.
WATERWAY_TAG_MAX_DISTANCE_M = 300 * 0.3048  # 300 feet in meters (~91.44)

# Tag prefixes generated by the reverse geocoding system
# This is the SINGLE SOURCE OF TRUTH for all reverse geocoding tag prefixes
# Used by:
# - ReverseGeocodingTagGenerator to register system tags
# - regeocode_features management command to filter old tags
REVERSE_GEOCODING_TAG_PREFIXES = [
    # Administrative boundaries
    'city',
    'state',
    'country',
    'county',
    
    # Water bodies
    'lake',
    'ocean',
    
    # Recreation
    'ski-resort',
    
    # Protected areas (from classify_protected_area in protected_areas.py)
    'national-park',
    'national-monument',
    'national-forest',
    'national-wildlife-refuge',
    'national-recreation-area',
    'national-historic-site',
    'national-seashore',
    'national-lakeshore',
    'state-park',
    'park',
    'wilderness',
    'protected-area',  # Default for unclassified protected areas
    'waterway',
]
