# Generated by Django 6.0a1 on 2025-11-29 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_activity', models.DateTimeField(blank=True, help_text='Last time the user was active on the site', null=True)),
            ],
            options={
                'db_table': 'users_userprofile',
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User-provided name/label for this API key', max_length=255)),
                ('key_prefix', models.CharField(db_index=True, help_text='First 8 characters of the key for display and lookup', max_length=8)),
                ('key_hash', models.CharField(help_text='SHA-256 hash of the full API key', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this API key was created')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When this API key was last used for authentication', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this API key is active (can be used for authentication)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_apikey',
                'indexes': [models.Index(fields=['key_prefix'], name='users_apike_key_pre_70468c_idx')],
                'unique_together': {('user', 'key_prefix')},
            },
        ),
    ]
