# Generated by Django 6.0a1 on 2025-11-27 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_activity', models.DateTimeField(blank=True, help_text='Last time the user was active on the site', null=True)),
            ],
            options={
                'db_table': 'users_userprofile',
            },
        ),
    ]
