# Generated by Django 6.0.3 on 2026-03-14 20:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracker_secret', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('settings', models.JSONField(default=dict)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared with specific users'), ('public', 'Public')], default='private', max_length=20)),
                ('share_params_with_recipients', models.BooleanField(default=False)),
                ('share_params_with_world', models.BooleanField(default=False)),
                ('geometry', models.JSONField(default=dict)),
                ('point_params', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LiveTrackGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hidden_in_list', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared with specific users'), ('public', 'Public')], default='private', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_track_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LiveTrackGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_members', to='live_track.livetrackgroup')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='live_track.livetrack')),
            ],
        ),
        migrations.CreateModel(
            name='LiveTrackGroupShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_entries', to='live_track.livetrackgroup')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_track_group_shares_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiveTrackGroupWorldShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='world_share', to='live_track.livetrackgroup')),
            ],
        ),
        migrations.CreateModel(
            name='LiveTrackMapVisibilityPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_track_ids', models.JSONField(default=list)),
                ('hidden_group_ids', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_track_map_visibility_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiveTrackShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_track_shares_received', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_entries', to='live_track.livetrack')),
            ],
        ),
        migrations.CreateModel(
            name='LiveTrackSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='live_track.livetrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_track_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiveTrackWorldShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='world_share', to='live_track.livetrack')),
            ],
        ),
        migrations.AddConstraint(
            model_name='livetrack',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='live_track_unique_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='livetrackgroup',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='live_track_group_unique_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='livetrackgroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'track'), name='live_track_group_member_unique'),
        ),
        migrations.AddConstraint(
            model_name='livetrackgroupshare',
            constraint=models.UniqueConstraint(fields=('group', 'shared_with'), name='live_track_group_share_unique'),
        ),
        migrations.AddConstraint(
            model_name='livetrackshare',
            constraint=models.UniqueConstraint(fields=('track', 'shared_with'), name='live_track_share_unique'),
        ),
        migrations.AddConstraint(
            model_name='livetracksubscription',
            constraint=models.UniqueConstraint(fields=('user', 'track'), name='live_track_subscription_unique'),
        ),
    ]
