# Generated by Django 6.0.3 on 2026-03-14 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_track', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livetrackgroup',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared with specific users'), ('public', 'Public')], default='private', max_length=20),
        ),
        migrations.CreateModel(
            name='LiveTrackGroupWorldShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='world_share', to='live_track.livetrackgroup')),
            ],
        ),
        migrations.CreateModel(
            name='LiveTrackGroupShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_entries', to='live_track.livetrackgroup')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_track_group_shares_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'shared_with'), name='live_track_group_share_unique')],
            },
        ),
    ]
