# Generated by Django 6.0.3 on 2026-03-24 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_track', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livetrackgroup',
            old_name='hidden_in_list',
            new_name='hidden',
        ),
    ]
