# Generated by Django 6.0.3 on 2026-03-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetrack',
            name='hauk_password',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
