# Generated by Django 6.0.3

from django.db import migrations, models


def backfill_settings_from_color(apps, schema_editor):
    LiveTrack = apps.get_model("live_track", "LiveTrack")
    for track in LiveTrack.objects.all():
        track.settings = {"color": track.color or "#3388ff"}
        track.save(update_fields=["settings"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("live_track", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="livetrack",
            name="settings",
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(backfill_settings_from_color, noop),
        migrations.RemoveField(
            model_name="livetrack",
            name="color",
        ),
    ]
