# Generated by Django 6.0.3 on 2026-03-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetrackgroup',
            name='hidden_in_list',
            field=models.BooleanField(default=False),
        ),
    ]
