# Generated by Django 6.0.3 on 2026-03-14 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_track', '0002_add_group_hidden_in_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTrackMapVisibilityPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_track_ids', models.JSONField(default=list)),
                ('hidden_group_ids', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_track_map_visibility_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
