# Generated by Django 6.0.3 on 2026-03-09 23:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_track', '0002_settings_remove_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livetrack',
            name='share_params_with_recipients',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livetrack',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared with specific users'), ('public', 'Public')], default='private', max_length=20),
        ),
        migrations.CreateModel(
            name='LiveTrackGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_track_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LiveTrackGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_members', to='live_track.livetrackgroup')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='live_track.livetrack')),
            ],
        ),
        migrations.CreateModel(
            name='LiveTrackGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_members', to='live_track.livetrackgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_track_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiveTrackShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_track_shares_received', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_entries', to='live_track.livetrack')),
            ],
        ),
        migrations.CreateModel(
            name='LiveTrackSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='live_track.livetrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_track_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='livetrackgroup',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='live_track_group_unique_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='livetrackgroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'track'), name='live_track_group_member_unique'),
        ),
        migrations.AddConstraint(
            model_name='livetrackgroupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='live_track_group_membership_unique'),
        ),
        migrations.AddConstraint(
            model_name='livetrackshare',
            constraint=models.UniqueConstraint(fields=('track', 'shared_with'), name='live_track_share_unique'),
        ),
        migrations.AddConstraint(
            model_name='livetracksubscription',
            constraint=models.UniqueConstraint(fields=('user', 'track'), name='live_track_subscription_unique'),
        ),
    ]
