# Generated by Django 6.0.3 on 2026-03-29 23:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_track', '0002_rename_hidden_in_list_to_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetracksubscription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
