# Generated by Django 6.0.3

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_track', '0003_visibility_sharing_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTrackPublicShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_share', to='live_track.livetrack')),
            ],
            options={
                'app_label': 'live_track',
            },
        ),
    ]
