# Generated by Django 6.0.3 on 2026-09-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_track', '0004_livetrackgroupinternalshare_livetrackinternalshare'),
        ('api', '0009_copy_legacy_shares_to_sharelink'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='livetrackgroupinternalshare',
            name='lt_grp_int_user_created_idx',
        ),
        migrations.RemoveConstraint(
            model_name='livetrackgroupshare',
            name='live_track_group_share_unique',
        ),
        migrations.RemoveField(
            model_name='livetrackgroupworldshare',
            name='group',
        ),
        migrations.RemoveIndex(
            model_name='livetrackinternalshare',
            name='lt_int_user_created_idx',
        ),
        migrations.RemoveConstraint(
            model_name='livetrackshare',
            name='live_track_share_unique',
        ),
        migrations.RemoveField(
            model_name='livetrackworldshare',
            name='track',
        ),
        migrations.RemoveField(
            model_name='livetrackgroupinternalshare',
            name='group',
        ),
        migrations.RemoveField(
            model_name='livetrackgroupinternalshare',
            name='user',
        ),
        migrations.RemoveField(
            model_name='livetrackgroupshare',
            name='group',
        ),
        migrations.RemoveField(
            model_name='livetrackgroupshare',
            name='shared_with',
        ),
        migrations.DeleteModel(
            name='LiveTrackGroupWorldShare',
        ),
        migrations.RemoveField(
            model_name='livetrackinternalshare',
            name='track',
        ),
        migrations.RemoveField(
            model_name='livetrackinternalshare',
            name='user',
        ),
        migrations.RemoveField(
            model_name='livetrackshare',
            name='shared_with',
        ),
        migrations.RemoveField(
            model_name='livetrackshare',
            name='track',
        ),
        migrations.DeleteModel(
            name='LiveTrackWorldShare',
        ),
        migrations.DeleteModel(
            name='LiveTrackGroupInternalShare',
        ),
        migrations.DeleteModel(
            name='LiveTrackGroupShare',
        ),
        migrations.DeleteModel(
            name='LiveTrackInternalShare',
        ),
        migrations.DeleteModel(
            name='LiveTrackShare',
        ),
    ]
