# Generated by Django 6.0.3

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_track', '0004_livetrackpublicshare'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LiveTrackPublicShare',
            new_name='LiveTrackWorldShare',
        ),
    ]
