# Generated by Django 6.0.3 on 2026-09-09 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_track', '0005_delete_legacy_tracker_share_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTrackPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('timestamp_ms', models.BigIntegerField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('params', models.JSONField(default=dict)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_rows', to='live_track.livetrack')),
            ],
            options={
                'db_table': 'live_track_point',
                'ordering': ['timestamp_ms', 'seq'],
                'indexes': [models.Index(fields=['track', 'timestamp_ms', 'seq'], name='live_track_point_latest_idx')],
                'constraints': [models.UniqueConstraint(fields=('track', 'seq'), name='live_track_point_unique_track_seq')],
            },
        ),
    ]
