# Generated by Django 6.0.3 on 2026-09-09 13:09

from django.db import migrations


def _coord_timestamp_ms(coord):
    if not coord or len(coord) < 3:
        return 0
    try:
        return int(coord[2])
    except (TypeError, ValueError):
        return 0


def _lon_lat(coord):
    if not coord or len(coord) < 2:
        return None
    try:
        return float(coord[0]), float(coord[1])
    except (TypeError, ValueError):
        return None


def copy_json_points_to_rows(apps, schema_editor):
    LiveTrack = apps.get_model("live_track", "LiveTrack")
    LiveTrackPoint = apps.get_model("live_track", "LiveTrackPoint")
    rows = []
    for track in LiveTrack.objects.iterator(chunk_size=200):
        geom = track.geometry if isinstance(track.geometry, dict) else {}
        coords = list(geom.get("coordinates") or [])
        raw_params = list(track.point_params or [])
        if len(raw_params) != len(coords):
            raw_params = [{} for _ in coords]
        seq = 0
        for coord, extra in zip(coords, raw_params):
            lon_lat = _lon_lat(coord)
            if lon_lat is None:
                continue
            lon, lat = lon_lat
            params = dict(extra) if isinstance(extra, dict) else {}
            rows.append(
                LiveTrackPoint(
                    track_id=track.id,
                    seq=seq,
                    timestamp_ms=_coord_timestamp_ms(coord),
                    lon=lon,
                    lat=lat,
                    params=params,
                )
            )
            seq += 1
        if len(rows) >= 1000:
            LiveTrackPoint.objects.bulk_create(rows, batch_size=1000)
            rows = []
    if rows:
        LiveTrackPoint.objects.bulk_create(rows, batch_size=1000)


def copy_rows_back_to_json(apps, schema_editor):
    LiveTrack = apps.get_model("live_track", "LiveTrack")
    LiveTrackPoint = apps.get_model("live_track", "LiveTrackPoint")
    for track in LiveTrack.objects.iterator(chunk_size=200):
        points = list(
            LiveTrackPoint.objects.filter(track_id=track.id).order_by("timestamp_ms", "seq")
        )
        coords = [[point.lon, point.lat, point.timestamp_ms] for point in points]
        params = [point.params if isinstance(point.params, dict) else {} for point in points]
        track.geometry = {"type": "LineString", "coordinates": coords}
        track.point_params = params
        track.save(update_fields=["geometry", "point_params"])
    LiveTrackPoint.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('live_track', '0006_livetrackpoint'),
    ]

    operations = [
        migrations.RunPython(copy_json_points_to_rows, copy_rows_back_to_json),
    ]
