# Generated by Django 6.0.3 on 2026-09-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_track', '0007_backfill_live_track_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livetrack',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='livetrack',
            name='point_params',
        ),
    ]
